### ISSUE TITLE
Exception when handling non-existing file case

### ISSUE THREAD

**Issue by vloothuis** [daveyarwood/boot-github#1]
I get an error on this line:

https://github.com/daveyarwood/boot-github/blob/e2b14623d4abfaa47d331cc72bebe438f60039d7/src/io/djy/boot_github.clj#L141

Error:

```
           io.djy.boot-github/eval4797/fn/fn/fn/fn          boot_github.clj:  141
                                               ...
java.lang.IllegalArgumentException: No matching field found: getName for class java.lang.String
        clojure.lang.ExceptionInfo: No matching field found: getName for class java.lang.String
```

**Comment by daveyarwood** [comment]
Thanks for the heads up! This is fixed in 0.1.4, so you should get a more informative error message if the file doesn't exist now.
